### ISSUE TITLE
How to apply more than one post processor?

### ISSUE THREAD

**Issue by bluemix** [wasabeef/fresco-processors#7]
Hello,
I was using previously using Picasso, by which I can add multiple transformations (combined) to the image. 
Here, in Fresco, I tried to do the same, but, it only applies that last post processor added, ignoring any previously added ones.
I hope, you have an idea of how to do this with Fresco.

thanks in advance.

**Comment by alfdev** [comment]
No one answered you? :( 

Have you found a solution?

I'm also interested in this issue.

**Comment by bluemix** [comment]
As far as I remember, the solution is not as easy as with Picasso.
So, I returned to Picasso, and used OkHttp also, since both of them from Square.
Besides, from my notices, Picasso is simpler and _slightly_ faster than Fresco.

**Comment by alfdev** [comment]
But Fresco seems to have a great memory management...

**Comment by bluemix** [comment]
I don't think _great_ is the big difference between them in terms of memory management. Both of them are very good.

**Comment by alfdev** [comment]
i'll try picasso as soon as possible, for now i'm using glide.

**Comment by gbero** [comment]
I've implemented BaseRepeatedPostProcessor and keep a list of the current attached postprocessors.

Calling postprocessor.process(dest, dest); ensure that every post processor will be applied to the current transformation.

TODO :  Check to not add the same post processor twice

```
public class BaseRepeatedPostProcessorImpl extends BaseRepeatedPostProcessor {

  List<BasePostprocessor> postprocessors = new ArrayList<>();

  public void apply(BasePostprocessor postprocessor) {
    postprocessors.add(postprocessor);
    update();
  }

  @Override
  public void process(Bitmap dest, Bitmap source) {
    Canvas canvas = new Canvas(dest);
    Paint paint = new Paint();
    canvas.drawBitmap(source, 0, 0, paint);

    for (BasePostprocessor postprocessor : postprocessors) {
      postprocessor.process(dest, dest);
    }
  }
}
```

Call with : 

```
BaseRepeatedPostProcessorImpl repeatedPostProcessor = new BaseRepeatedPostProcessorImpl();
    ImageRequest imageRequest = ImageRequestBuilder.newBuilderWithSource(uri)
                                    .setPostprocessor(repeatedPostProcessor)
                                    .build();

    DraweeController controller = Fresco.newDraweeControllerBuilder()
                                      .setImageRequest(imageRequest)
                                      .build();

    mainPicture.setController(controller);
    repeatedPostProcessor.apply(myPostProcessor);
    repeatedPostProcessor.apply(myPostProcessor2);
    repeatedPostProcessor.apply(myPostProcessor3);
```
